--ARCHIVO PARA CONSTRUIR BASE DE DATO TCDB
--MATIAS RODRIGUEZ, JUAN ROJAS, ANGEL SILVA

--CREACION DE TABLAS

CREATE TABLE TCDB_REGION(
    ID_REGION NUMBER,
    NOMBRE VARCHAR2(30),
    CONSTRAINT PK_REGION PRIMARY KEY(ID_REGION)
);

CREATE TABLE TCDB_CIUDAD(
    ID_CIUDAD NUMBER,
    NOMBRE VARCHAR2(50),
    ID_REGION NUMBER,
    CONSTRAINT PK_CIUDAD PRIMARY KEY(ID_CIUDAD),
    CONSTRAINT FK_CIUDAD_REGION FOREIGN KEY(ID_REGION) REFERENCES TCDB_REGION(ID_REGION)
);

CREATE TABLE TCDB_INSTITUCION (
    ID_INSTITUCION NUMBER,
    TIPO_INSTITUCION VARCHAR2(30),
    NOMBRE VARCHAR2(50),
    CONSTRAINT PK_INSTITUCION PRIMARY KEY(ID_INSTITUCION)
);

CREATE TABLE TCDB_SEDE_INSTITUCION (
    ID_SEDE NUMBER,
    NOMBRE_SEDE VARCHAR2(50),
    ID_INSTITUCION NUMBER,
    ID_CIUDAD NUMBER,
    CONSTRAINT PK_SEDE_INSTITUCION PRIMARY KEY(ID_SEDE),
    CONSTRAINT FK_SEDE_INSTITUCION FOREIGN KEY(ID_INSTITUCION)
    REFERENCES TCDB_INSTITUCION(ID_INSTITUCION),
    CONSTRAINT FK_SEDE_CIUDAD FOREIGN KEY(ID_CIUDAD)
    REFERENCES TCDB_CIUDAD(ID_CIUDAD)
);

