--ARCHIVO PARA CONSTRUIR BASE DE DATO TCDB
--MATIAS RODRIGUEZ, JUAN ROJAS, ANGEL SILVA

--BORRADO DE TABLAS

DROP TABLE TCDB_ARRIENDO;
DROP TABLE TCDB_HABITACION;
DROP TABLE TCDB_INMUEBLE;
DROP TABLE TCDB_USUARIO;
DROP TABLE TCDB_UBICACION;
DROP TABLE TCDB_SEDE_INSTITUCION;
DROP TABLE TCDB_INSTITUCION;
DROP TABLE TCDB_CIUDAD;
DROP TABLE TCDB_REGION;

--CREACION DE TABLAS

CREATE TABLE TCDB_REGION(
    ID_REGION NUMBER,
    NOMBRE VARCHAR2(30),
    CONSTRAINT PK_REGION PRIMARY KEY(ID_REGION)
);

CREATE TABLE TCDB_CIUDAD(
    ID_CIUDAD NUMBER,
    NOMBRE VARCHAR2(50),
    ID_REGION NUMBER,
    CONSTRAINT PK_CIUDAD PRIMARY KEY(ID_CIUDAD),
    CONSTRAINT FK_CIUDAD_REGION FOREIGN KEY(ID_REGION) REFERENCES TCDB_REGION(ID_REGION)
);

CREATE TABLE TCDB_INSTITUCION (
    ID_INSTITUCION NUMBER,
    TIPO_INSTITUCION VARCHAR2(30),
    NOMBRE VARCHAR2(50),
    CONSTRAINT PK_INSTITUCION PRIMARY KEY(ID_INSTITUCION)
);

CREATE TABLE TCDB_SEDE_INSTITUCION (
    ID_SEDE NUMBER,
    NOMBRE_SEDE VARCHAR2(50),
    ID_INSTITUCION NUMBER,
    ID_CIUDAD NUMBER,
    CONSTRAINT PK_SEDE_INSTITUCION PRIMARY KEY(ID_SEDE),
    CONSTRAINT FK_SEDE_INSTITUCION FOREIGN KEY(ID_INSTITUCION)
    REFERENCES TCDB_INSTITUCION(ID_INSTITUCION),
    CONSTRAINT FK_SEDE_CIUDAD FOREIGN KEY(ID_CIUDAD)
    REFERENCES TCDB_CIUDAD(ID_CIUDAD)
);

CREATE TABLE TCDB_UBICACION(
    ID_UBICACION NUMBER,
    CALLE VARCHAR2(100),
    NUM_CALLE NUMBER,
    ID_CIUDAD NUMBER,
    CONSTRAINT PK_UBICACION PRIMARY KEY(ID_UBICACION),
    CONSTRAINT FK_UBICACION_CIUDAD FOREIGN KEY(ID_CIUDAD) REFERENCES TCDB_CIUDAD(ID_CIUDAD)
);

CREATE TABLE TCDB_USUARIO(
    ID_USUARIO NUMBER,
    ROL_USUARIO VARCHAR2(30),
    NOMBRE VARCHAR2(50),
    APELLIDO1 VARCHAR2(30),
    APELLIDO2 VARCHAR2(30),
    CORREO VARCHAR2(50),
    CONTRASENIA VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    IMAGEN_PERFIL VARCHAR2(100),
    ID_INSTITUCION NUMBER,
    CALLE VARCHAR2(100),
    NUM_CALLE NUMBER,
    ID_CIUDAD NUMBER,
    CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO),
    CONSTRAINT FK_USUARIO_INSTITUCION FOREIGN KEY(ID_INSTITUCION) REFERENCES TCDB_SEDE_INSTITUCION(ID_SEDE),
    CONSTRAINT FK_USUARIO_CIUDAD FOREIGN KEY(ID_CIUDAD) REFERENCES TCDB_CIUDAD(ID_CIUDAD)
);

CREATE TABLE TCDB_INMUEBLE(
    ID_INMUEBLE NUMBER,
    NOMBRE VARCHAR2(50),
    TIPO_INMUEBLE VARCHAR2(50),
    DESCRIPCION VARCHAR2(500),
    NUM_HABITACIONES NUMBER,
    NUM_BANIOS NUMBER,
    ID_ARRENDADOR NUMBER,
    ID_UBICACION NUMBER,
    CONSTRAINT PK_INMUEBLE PRIMARY KEY(ID_INMUEBLE),
    CONSTRAINT FK_INMUEBLE_ARRENDADOR FOREIGN KEY(ID_ARRENDADOR) REFERENCES TCDB_USUARIO(ID_USUARIO),
    CONSTRAINT FK_INMUEBLE_UBICACION FOREIGN KEY(ID_UBICACION) REFERENCES TCDB_UBICACION(ID_UBICACION)
);


CREATE TABLE TCDB_HABITACION(
    ID_HABITACION NUMBER,
    NOMBRE VARCHAR2(50),
    ID_INMUEBLE NUMBER,
    DESCRIPCION VARCHAR2(200),
    CONSTRAINT PK_HABITACION PRIMARY KEY(ID_HABITACION),
    CONSTRAINT FK_HABITACION_INMUEBLE FOREIGN KEY(ID_INMUEBLE) REFERENCES TCDB_INMUEBLE(ID_INMUEBLE)
);

CREATE TABLE TCDB_CONTACTO(
    ID_CONTACTO NUMBER,
    TELEFONO VARCHAR2(20),
    WHATSAPP VARCHAR2(20),
    PAGINA_WEB VARCHAR2(100),
    CORREO_ELECTRONICO VARCHAR2(100),
    CONSTRAINT PK_CONTACTO PRIMARY KEY(ID_CONTACTO)
);

CREATE TABLE TCDB_ARRIENDO(
    ID_ARRIENDO NUMBER,
    TIPO_ARRIENDO VARCHAR2(20),
    ID_INMUEBLE NUMBER,
    ID_HABITACION NUMBER,
    PRECIO NUMBER,
    ID_CONTACTO NUMBER,
    ESTADO VARCHAR2(30),
    CONSTRAINT PK_ARRIENDO PRIMARY KEY(ID_ARRIENDO),
    CONSTRAINT FK_ARRIENDO_INMUEBLE FOREIGN KEY(ID_INMUEBLE) REFERENCES TCDB_INMUEBLE(ID_INMUEBLE),
    CONSTRAINT FK_ARRIENDO_HABITACION FOREIGN KEY(ID_HABITACION) REFERENCES TCDB_HABITACION(ID_HABITACION),
    CONSTRAINT FK_ARRIENDO_CONTACTO FOREIGN KEY(ID_CONTACTO)REFERENCES TCDB_CONTACTO(ID_CONTACTO)
);
